<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class LessonsTableSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $lessons = [
            // Beginner Python Lessons
            [
                'lesson_id' => 1,
                'created_by' => 1,
                'title' => 'Introduction to Python Programming',
                'content' => "Welcome to Python Programming! This comprehensive course will take you from complete beginner to confident Python programmer.",
                'content_type' => 'markdown',
                'difficulty' => 'beginner',
                'estimated_duration' => 45,
                'video_url' => 'https://example.com/videos/python-intro',
                'status' => 'active',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 100,
                'required_exercises' => 2,
                'required_tests' => 1,
                'min_exercise_score_percent' => 70.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 2,
                'created_by' => 1,
                'title' => 'Python Variables and Data Types',
                'content' => "Master the fundamentals of Python data types and learn how to work with different kinds of data in your programs.",
                'content_type' => 'markdown',
                'difficulty' => 'beginner',
                'estimated_duration' => 35,
                'video_url' => 'https://example.com/videos/python-variables',
                'status' => 'active',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 80,
                'required_exercises' => 3,
                'required_tests' => 1,
                'min_exercise_score_percent' => 70.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 3,
                'created_by' => 1,
                'title' => 'Working with Strings in Python',
                'content' => "Learn everything about string manipulation, formatting, and powerful string methods in Python.",
                'content_type' => 'markdown',
                'difficulty' => 'beginner',
                'estimated_duration' => 40,
                'video_url' => 'https://example.com/videos/python-strings',
                'status' => 'active',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 90,
                'required_exercises' => 2,
                'required_tests' => 1,
                'min_exercise_score_percent' => 75.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 4,
                'created_by' => 1,
                'title' => 'Python Lists and Basic Operations',
                'content' => "Dive deep into Python lists - one of the most important and versatile data structures in Python.",
                'content_type' => 'markdown',
                'difficulty' => 'beginner',
                'estimated_duration' => 50,
                'video_url' => 'https://example.com/videos/python-lists',
                'status' => 'active',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 100,
                'required_exercises' => 3,
                'required_tests' => 1,
                'min_exercise_score_percent' => 70.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 5,
                'created_by' => 1,
                'title' => 'Python If Statements and Conditions',
                'content' => "Learn how to make your programs smart with conditional logic and decision-making structures.",
                'content_type' => 'markdown',
                'difficulty' => 'beginner',
                'estimated_duration' => 40,
                'video_url' => 'https://example.com/videos/python-conditionals',
                'status' => 'active',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 90,
                'required_exercises' => 3,
                'required_tests' => 1,
                'min_exercise_score_percent' => 75.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Intermediate Python Lessons
            [
                'lesson_id' => 6,
                'created_by' => 1,
                'title' => 'Python Loops: For and While',
                'content' => "Master iteration in Python with for loops, while loops, and advanced loop control techniques.",
                'content_type' => 'markdown',
                'difficulty' => 'intermediate',
                'estimated_duration' => 55,
                'video_url' => 'https://example.com/videos/python-loops',
                'status' => 'active',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 120,
                'required_exercises' => 4,
                'required_tests' => 1,
                'min_exercise_score_percent' => 75.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 7,
                'created_by' => 1,
                'title' => 'Python Functions and Parameters',
                'content' => "Create reusable, modular code with functions. Learn about parameters, return values, and scope.",
                'content_type' => 'markdown',
                'difficulty' => 'intermediate',
                'estimated_duration' => 60,
                'video_url' => 'https://example.com/videos/python-functions',
                'status' => 'active',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 140,
                'required_exercises' => 4,
                'required_tests' => 2,
                'min_exercise_score_percent' => 75.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 8,
                'created_by' => 1,
                'title' => 'Python Dictionaries and Key-Value Pairs',
                'content' => "Work with dictionaries to store and manipulate data using key-value pairs efficiently.",
                'content_type' => 'markdown',
                'difficulty' => 'intermediate',
                'estimated_duration' => 50,
                'video_url' => 'https://example.com/videos/python-dictionaries',
                'status' => 'active',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 130,
                'required_exercises' => 3,
                'required_tests' => 1,
                'min_exercise_score_percent' => 75.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 9,
                'created_by' => 1,
                'title' => 'File Handling in Python',
                'content' => "Learn to read from and write to files, handle different file formats, and work with file paths.",
                'content_type' => 'markdown',
                'difficulty' => 'intermediate',
                'estimated_duration' => 45,
                'video_url' => 'https://example.com/videos/python-files',
                'status' => 'active',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 150,
                'required_exercises' => 3,
                'required_tests' => 1,
                'min_exercise_score_percent' => 80.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 10,
                'created_by' => 1,
                'title' => 'Exception Handling with Try-Except',
                'content' => "Write robust code that gracefully handles errors and unexpected situations.",
                'content_type' => 'markdown',
                'difficulty' => 'intermediate',
                'estimated_duration' => 40,
                'video_url' => 'https://example.com/videos/python-exceptions',
                'status' => 'active',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 120,
                'required_exercises' => 3,
                'required_tests' => 1,
                'min_exercise_score_percent' => 75.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Advanced Python Lessons
            [
                'lesson_id' => 11,
                'created_by' => 1,
                'title' => 'Python Classes and Object-Oriented Programming',
                'content' => "Master Object-Oriented Programming concepts including classes, objects, inheritance, and polymorphism.",
                'content_type' => 'markdown',
                'difficulty' => 'advanced',
                'estimated_duration' => 75,
                'video_url' => 'https://example.com/videos/python-oop',
                'status' => 'active',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 200,
                'required_exercises' => 5,
                'required_tests' => 2,
                'min_exercise_score_percent' => 80.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 12,
                'created_by' => 1,
                'title' => 'Working with Python Modules and Packages',
                'content' => "Learn to organize code into modules, use built-in libraries, and work with third-party packages.",
                'content_type' => 'markdown',
                'difficulty' => 'advanced',
                'estimated_duration' => 55,
                'video_url' => 'https://example.com/videos/python-modules',
                'status' => 'active',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 180,
                'required_exercises' => 4,
                'required_tests' => 1,
                'min_exercise_score_percent' => 80.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 13,
                'created_by' => 1,
                'title' => 'Python List Comprehensions and Generators',
                'content' => "Write more Pythonic code with list comprehensions, generator expressions, and generator functions.",
                'content_type' => 'markdown',
                'difficulty' => 'advanced',
                'estimated_duration' => 50,
                'video_url' => 'https://example.com/videos/python-comprehensions',
                'status' => 'active',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 170,
                'required_exercises' => 4,
                'required_tests' => 1,
                'min_exercise_score_percent' => 80.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 14,
                'created_by' => 1,
                'title' => 'Python Decorators and Advanced Functions',
                'content' => "Explore advanced function concepts including decorators, lambda functions, and functional programming.",
                'content_type' => 'markdown',
                'difficulty' => 'advanced',
                'estimated_duration' => 60,
                'video_url' => 'https://example.com/videos/python-decorators',
                'status' => 'active',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 190,
                'required_exercises' => 4,
                'required_tests' => 2,
                'min_exercise_score_percent' => 80.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 15,
                'created_by' => 1,
                'title' => 'Data Analysis with Python and Pandas',
                'content' => "Learn data analysis and manipulation using the powerful Pandas library.",
                'content_type' => 'markdown',
                'difficulty' => 'advanced',
                'estimated_duration' => 90,
                'video_url' => 'https://example.com/videos/python-pandas',
                'status' => 'active',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 220,
                'required_exercises' => 5,
                'required_tests' => 2,
                'min_exercise_score_percent' => 85.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Draft/Inactive Lessons
            [
                'lesson_id' => 16,
                'created_by' => 1,
                'title' => 'Python Web Scraping Basics',
                'content' => "Learn to extract data from websites using requests and BeautifulSoup libraries.",
                'content_type' => 'markdown',
                'difficulty' => 'intermediate',
                'estimated_duration' => 65,
                'video_url' => null,
                'status' => 'draft',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 160,
                'required_exercises' => 3,
                'required_tests' => 1,
                'min_exercise_score_percent' => 75.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 17,
                'created_by' => 1,
                'title' => 'Python GUI Development with Tkinter',
                'content' => "Create desktop applications with graphical user interfaces using Tkinter.",
                'content_type' => 'markdown',
                'difficulty' => 'advanced',
                'estimated_duration' => 90,
                'video_url' => 'https://example.com/videos/python-gui',
                'status' => 'inactive',
                'ai_generated' => 0,
                'ai_source_url' => null,
                'completion_reward_points' => 200,
                'required_exercises' => 4,
                'required_tests' => 1,
                'min_exercise_score_percent' => 80.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('lessons')->insert($lessons);

        // Now insert lesson sections
        $this->insertLessonSections($now);
    }

    private function insertLessonSections($now)
    {
        $sections = [
            // Lesson 1: Introduction to Python Programming
            [
                'lesson_id' => 1,
                'title' => 'What is Python?',
                'content' => "# What is Python?\n\nPython is a high-level, interpreted programming language created by Guido van Rossum in 1991. It's known for:\n\n- **Simple, readable syntax** - Python code reads almost like English\n- **Versatility** - Used for web development, data science, AI, automation, and more\n- **Large community** - Thousands of libraries and frameworks available\n- **Cross-platform** - Runs on Windows, Mac, Linux, and more\n\nPython is one of the most popular programming languages in the world and is perfect for beginners!",
                'order_index' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 1,
                'title' => 'Your First Python Program',
                'content' => "# Hello, World!\n\nLet's write your first Python program:\n\n```python\nprint('Hello, World!')\n```\n\nThat's it! This simple line will display \"Hello, World!\" on your screen.\n\nLet's break it down:\n- `print()` is a built-in Python function that displays text\n- The text inside quotes ('Hello, World!') is called a **string**\n- You can use single quotes ('') or double quotes (\"\")",
                'order_index' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 1,
                'title' => 'Python Syntax Basics',
                'content' => "# Python Syntax Rules\n\nPython has some important syntax rules:\n\n## 1. Indentation Matters\nPython uses indentation (spaces/tabs) to define code blocks:\n\n```python\nif True:\n    print('This is indented')  # 4 spaces\n    print('This too')\n```\n\n## 2. Case Sensitive\nPython distinguishes between uppercase and lowercase:\n\n```python\nname = 'Alice'  # This is different from\nName = 'Bob'    # this variable\n```\n\n## 3. Comments\nUse # for single-line comments:\n\n```python\n# This is a comment\nprint('Hello')  # This is also a comment\n```",
                'order_index' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 1,
                'title' => 'Variables Introduction',
                'content' => "# Variables in Python\n\nVariables are containers that store data values:\n\n```python\nname = 'Alice'\nage = 25\nheight = 5.6\nis_student = True\n```\n\nKey points about variables:\n- No need to declare variable types (Python figures it out)\n- Variable names should be descriptive\n- Use lowercase with underscores for multi-word names: `user_name`\n- Cannot start with numbers: `2name` ❌, `name2` ✅\n- Cannot use Python keywords: `if`, `for`, `while`, etc.",
                'order_index' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 1,
                'title' => 'Getting User Input',
                'content' => "# User Input in Python\n\nUse `input()` to get data from users:\n\n```python\nname = input('What is your name? ')\nprint('Hello, ' + name + '!')\n```\n\nThe `input()` function:\n- Always returns a string\n- Can display a prompt message\n- Waits for the user to press Enter\n\n## Converting Input Types\n\n```python\nage = input('Enter your age: ')  # This is a string\nage = int(age)  # Convert to integer\n\n# Or do it in one line:\nage = int(input('Enter your age: '))\n```",
                'order_index' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Lesson 2: Python Variables and Data Types
            [
                'lesson_id' => 2,
                'title' => 'Integer Data Type',
                'content' => "# Integers (int)\n\nIntegers are whole numbers without decimal points:\n\n```python\nage = 25\nyear = 2024\ntemperature = -5\ncount = 0\n```\n\n## Integer Operations\n\n```python\nx = 10\ny = 3\n\nprint(x + y)   # Addition: 13\nprint(x - y)   # Subtraction: 7\nprint(x * y)   # Multiplication: 30\nprint(x / y)   # Division: 3.333...\nprint(x // y)  # Floor division: 3\nprint(x % y)   # Modulus (remainder): 1\nprint(x ** y)  # Exponentiation: 1000\n```",
                'order_index' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 2,
                'title' => 'Float Data Type',
                'content' => "# Floats (float)\n\nFloats are numbers with decimal points:\n\n```python\nprice = 19.99\ntemperature = 36.6\npi = 3.14159\npercentage = 0.85\n```\n\n## Float Precision\n\n```python\nresult = 0.1 + 0.2\nprint(result)  # 0.30000000000000004 (floating point precision issue)\n\n# Round to specific decimal places\nprint(round(result, 2))  # 0.3\n```\n\n## Scientific Notation\n\n```python\nlarge_number = 1e6  # 1,000,000\nsmall_number = 1e-6  # 0.000001\n```",
                'order_index' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 2,
                'title' => 'String Data Type',
                'content' => "# Strings (str)\n\nStrings are sequences of characters:\n\n```python\nname = 'Alice'\nmessage = \"Hello, World!\"\nquote = '''This is a\nmulti-line string'''\n```\n\n## String Basics\n\n```python\n# Concatenation\nfirst = 'John'\nlast = 'Doe'\nfull_name = first + ' ' + last  # 'John Doe'\n\n# Repetition\nprint('Ha' * 3)  # 'HaHaHa'\n\n# Length\ntext = 'Python'\nprint(len(text))  # 6\n\n# Accessing characters\nprint(text[0])   # 'P' (first character)\nprint(text[-1])  # 'n' (last character)\n```",
                'order_index' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 2,
                'title' => 'Boolean Data Type',
                'content' => "# Booleans (bool)\n\nBooleans represent True or False values:\n\n```python\nis_active = True\nis_logged_in = False\nhas_permission = True\n```\n\n## Boolean Operations\n\n```python\n# Comparison operators return booleans\nprint(5 > 3)   # True\nprint(5 == 5)  # True\nprint(5 != 3)  # True\n\n# Logical operators\nx = True\ny = False\n\nprint(x and y)  # False (both must be True)\nprint(x or y)   # True (at least one is True)\nprint(not x)    # False (opposite of x)\n```\n\n## Truthy and Falsy Values\n\n```python\nbool(0)      # False\nbool('')     # False (empty string)\nbool([])     # False (empty list)\nbool(1)      # True\nbool('text') # True\n```",
                'order_index' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 2,
                'title' => 'Type Conversion',
                'content' => "# Converting Between Data Types\n\nPython allows you to convert between different data types:\n\n## String to Number\n\n```python\nage_str = '25'\nage_int = int(age_str)      # Convert to integer\nprice_str = '19.99'\nprice_float = float(price_str)  # Convert to float\n```\n\n## Number to String\n\n```python\nage = 25\nage_str = str(age)  # '25'\n```\n\n## Checking Types\n\n```python\nx = 42\nprint(type(x))  # <class 'int'>\n\ny = 3.14\nprint(type(y))  # <class 'float'>\n\nz = 'hello'\nprint(type(z))  # <class 'str'>\n\n# Check if variable is of specific type\nprint(isinstance(x, int))  # True\nprint(isinstance(x, str))  # False\n```",
                'order_index' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Lesson 3: Working with Strings
            [
                'lesson_id' => 3,
                'title' => 'String Methods - Case Manipulation',
                'content' => "# String Case Methods\n\nPython provides several methods to change string case:\n\n```python\ntext = 'hello world'\n\n# Convert to uppercase\nprint(text.upper())  # 'HELLO WORLD'\n\n# Convert to lowercase\nprint(text.lower())  # 'hello world'\n\n# Capitalize first letter\nprint(text.capitalize())  # 'Hello world'\n\n# Title case (capitalize each word)\nprint(text.title())  # 'Hello World'\n\n# Swap case\ntext2 = 'Hello World'\nprint(text2.swapcase())  # 'hELLO wORLD'\n```\n\n## Checking Case\n\n```python\nprint('HELLO'.isupper())  # True\nprint('hello'.islower())  # True\nprint('Hello'.istitle())  # True\n```",
                'order_index' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 3,
                'title' => 'String Methods - Finding and Replacing',
                'content' => "# Finding and Replacing Text\n\n## Finding Substrings\n\n```python\ntext = 'Python is awesome. Python is fun.'\n\n# Find position of substring\nprint(text.find('Python'))  # 0 (first occurrence)\nprint(text.find('is'))      # 7\nprint(text.find('Java'))    # -1 (not found)\n\n# Count occurrences\nprint(text.count('Python'))  # 2\nprint(text.count('is'))      # 2\n\n# Check if string starts/ends with\nprint(text.startswith('Python'))  # True\nprint(text.endswith('fun.'))      # True\n```\n\n## Replacing Text\n\n```python\ntext = 'I love Java'\nnew_text = text.replace('Java', 'Python')\nprint(new_text)  # 'I love Python'\n\n# Replace multiple occurrences\ntext2 = 'one two one three one'\nprint(text2.replace('one', 'ONE'))  # 'ONE two ONE three ONE'\n```",
                'order_index' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 3,
                'title' => 'String Formatting with f-strings',
                'content' => "# String Slicing\n\nExtract parts of strings using slice notation [start:end:step]:\n\n```python\ntext = 'Python Programming'\n\n# Basic slicing\nprint(text[0:6])    # 'Python' (chars 0-5)\nprint(text[7:18])   # 'Programming'\nprint(text[:6])     # 'Python' (from start)\nprint(text[7:])     # 'Programming' (to end)\nprint(text[:])      # 'Python Programming' (full string)\n\n# Negative indices (count from end)\nprint(text[-11:])   # 'Programming'\nprint(text[:-12])   # 'Python'\nprint(text[-11:-7]) # 'Prog'\n\n# Step parameter\nprint(text[::2])    # 'Pto rgamn' (every 2nd char)\nprint(text[::-1])   # 'gnimmargorP nohtyP' (reverse)\n```\n\n## Practical Examples\n\n```python\nemail = 'user@example.com'\nusername = email[:email.find('@')]  # 'user'\ndomain = email[email.find('@')+1:]  # 'example.com'\n```",
                'order_index' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 3,
                'title' => 'String Slicing',
                'content' => "# String Slicing\n\nExtract parts of strings using slice notation [start:end:step]:\n\n```python\ntext = 'Python Programming'\n\n# Basic slicing\nprint(text[0:6])    # 'Python' (chars 0-5)\nprint(text[7:18])   # 'Programming'\nprint(text[:6])     # 'Python' (from start)\nprint(text[7:])     # 'Programming' (to end)\nprint(text[:])      # 'Python Programming' (full string)\n\n# Negative indices (count from end)\nprint(text[-11:])   # 'Programming'\nprint(text[:-12])   # 'Python'\nprint(text[-11:-7]) # 'Prog'\n\n# Step parameter\nprint(text[::2])    # 'Pto rgamn' (every 2nd char)\nprint(text[::-1])   # 'gnimmargorP nohtyP' (reverse)\n```\n\n## Practical Examples\n\n```python\nemail = 'user@example.com'\nusername = email[:email.find('@')]  # 'user'\ndomain = email[email.find('@')+1:]  # 'example.com'\n```",
                'order_index' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id ' => 3,
                'title' => 'String Methods - Splitting and Joining',
                'content' => "# Splitting and Joining Strings\n\n## Splitting Strings\n\n```python\ntext = 'apple,banana,orange'\nfruits = text.split(',')  \nprint(fruits)  # ['apple', 'banana', 'orange']\n\n# Split by whitespace (default)\nsentence = 'Python is awesome'\nwords = sentence.split()\nprint(words)  # ['Python', 'is', 'awesome']\n\n# Split with max splits\ndata = 'a-b-c-d-e'\nprint(data.split('-', 2))  # ['a', 'b', 'c-d-e']\n\n# Split lines\nmultiline = 'Line 1\\nLine 2\\nLine 3'\nlines = multiline.splitlines()\nprint(lines)  # ['Line 1', 'Line 2', 'Line 3']\n```\n\n## Joining Strings\n\n```python\nfruits = ['apple', 'banana', 'orange']\nresult = ', '.join(fruits)\nprint(result)  # 'apple, banana, orange'\n\n# Join with different separator\nwords = ['Python', 'is', 'fun']\nprint(' '.join(words))   # 'Python is fun'\nprint('-'.join(words))   # 'Python-is-fun'\nprint(''.join(words))    # 'Pythonisfun'\n```",
                'order_index' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'lesson_id' => 4,
                'title' => 'Creating and Accessing Lists',
                'content' => "# Introduction to Lists\n\nLists are used to store multiple items in a single variable:\n\n```python\nfruits = ['apple', 'banana', 'cherry']\nnumbers = [1, 2, 3, 4, 5]\nmixed = ['Python', 3.10, True]\n```\n\n## Accessing Items\n- Indexing starts at 0: `fruits[0]` is 'apple'\n- Negative indexing: `fruits[-1]` is 'cherry'\n- Slicing: `numbers[1:3]` returns `[2, 3]`",
                'order_index' => 1,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'lesson_id' => 4,
                'title' => 'List Methods',
                'content' => "# Modifying Lists\n\nCommon methods to change a list:\n\n```python\nfruits = ['apple', 'banana']\n\n# Adding items\nfruits.append('orange')    # Adds to the end\nfruits.insert(1, 'pear')   # Adds at index 1\n\n# Removing items\nfruits.remove('apple')     # Removes specific item\nfruits.pop()               # Removes last item\n\n# Sorting\nfruits.sort()              # Alphabetical order\n```",
                'order_index' => 2,
                'created_at' => $now, 'updated_at' => $now,
            ],

            // Lesson 5: Python If Statements and Conditions
            [
                'lesson_id' => 5,
                'title' => 'If...Else Logic',
                'content' => "# Conditional Statements\n\nPython supports the usual logical conditions:\n\n```python\na = 33\nb = 200\n\nif b > a:\n    print('b is greater than a')\nelif a == b:\n    print('a and b are equal')\nelse:\n    print('a is greater than b')\n```\n\n**Note:** Indentation is mandatory in Python to define the scope of the code!",
                'order_index' => 1,
                'created_at' => $now, 'updated_at' => $now,
            ],

            // Lesson 6: Python Loops (Intermediate)
            [
                'lesson_id' => 6,
                'title' => 'For Loops and range()',
                'content' => "# For Loops\n\nA for loop is used for iterating over a sequence:\n\n```python\nfruits = ['apple', 'banana', 'cherry']\nfor x in fruits:\n    print(x)\n\n# Using range()\nfor i in range(5):    # 0 to 4\n    print(i)\n\nfor i in range(2, 10, 2): # Start, Stop, Step\n    print(i) # 2, 4, 6, 8\n```",
                'order_index' => 1,
                'created_at' => $now, 'updated_at' => $now,
            ],

            // Lesson 7: Python Functions
            [
                'lesson_id' => 7,
                'title' => 'Defining Functions',
                'content' => "# Functions\n\nA function is a block of code which only runs when it is called:\n\n```python\ndef my_function(fname, lname):\n    print(f'Hello {fname} {lname}')\n\nmy_function('Alan', 'Walker')\n\n# Return Values\ndef square(x):\n    return x * x\n\nresult = square(4) # 16\n```",
                'order_index' => 1,
                'created_at' => $now, 'updated_at' => $now,
            ],

            // Lesson 8: Dictionaries
            [
                'lesson_id' => 8,
                'title' => 'Dictionary Basics',
                'content' => "# Dictionaries\n\nDictionaries store data in key:value pairs:\n\n```python\nthisdict = {\n    'brand': 'Ford',\n    'model': 'Mustang',\n    'year': 1964\n}\n\n# Accessing items\nprint(thisdict['brand']) # Ford\n\n# Adding/Updating\nthisdict['color'] = 'red'\nthisdict.update({'year': 2020})\n```",
                'order_index' => 1,
                'created_at' => $now, 'updated_at' => $now,
            ],

            // Lesson 10: Exception Handling
            [
                'lesson_id' => 10,
                'title' => 'Try...Except Blocks',
                'content' => "# Error Handling\n\nPrevent your program from crashing when an error occurs:\n\n```python\ntry:\n    print(x)\nexcept NameError:\n    print('Variable x is not defined')\nexcept:\n    print('Something else went wrong')\nfinally:\n    print('The try...except is finished')\n```",
                'order_index' => 1,
                'created_at' => $now, 'updated_at' => $now,
            ],

            // Lesson 11: Classes and OOP (Advanced)
            [
                'lesson_id' => 11,
                'title' => 'Classes and Objects',
                'content' => "# Object Oriented Programming\n\nPython is an object oriented programming language:\n\n```python\nclass Person:\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age\n\n    def say_hi(self):\n        print(f'Hello, my name is {self.name}')\n\np1 = Person('John', 36)\np1.say_hi()\n```",
                'order_index' => 1,
                'created_at' => $now, 'updated_at' => $now,
            ],

            // Lesson 15: Data Analysis with Pandas
            [
                'lesson_id' => 15,
                'title' => 'Introduction to DataFrames',
                'content' => "# Pandas DataFrames\n\nA DataFrame is a 2-dimensional data structure, like a table:\n\n```python\nimport pandas as pd\n\ndata = {\n    'calories': [420, 380, 390],\n    'duration': [50, 40, 45]\n}\n\ndf = pd.DataFrame(data)\nprint(df)\n\n# Load from CSV\n# df = pd.read_csv('data.csv')\n```",
                'order_index' => 1,
                'created_at' => $now, 'updated_at' => $now,
            ],
        ];

        DB::table('lesson_sections')->insert($sections);
    }
}